### ISSUE TITLE
Support PowerShell

### ISSUE THREAD

**Issue by eum2o** [ctongfei/progressbar#136]
### Tested with
- PowerShell 5.1
- me.tongfei:progressbar:0.9.3
- Windows 10 21H2
- Java 17

### Problem
PowerShell seems to have problems with the used chars/encoding. The progress looks like this:

![image](https://user-images.githubusercontent.com/1593923/175026431-238d6ca4-3cbb-4afe-975a-e26505c305f5.png)
![image](https://user-images.githubusercontent.com/1593923/175026436-f81a5217-b156-4a03-b826-e5f483f5fc9a.png)

### How to Reproduce
I just used the declarative example
```
final List<Object> objects = IntStream.range(0, 100).mapToObj(i -> new Object()).toList();
for (Object entry : ProgressBar.wrap(objects, "Foobar")) {
	Thread.sleep(200);
	// Progress will be automatically monitored by a progress bar
}
```

**Comment by eum2o** [comment]
Maybe I created the issue too fast. By setting the style to ASCII, it works fine. Read this on http://tongfei.me/progressbar/styles/

Example:
```java
final List<Object> objects = IntStream.range(0, 100).mapToObj(i -> new Object()).toList();
ProgressBarBuilder pbb = new ProgressBarBuilder().setTaskName("Foobar")
		.setInitialMax(objects.size())
		.setStyle(ProgressBarStyle.ASCII);
try (ProgressBar pb = pbb.build()) {
	for (Object object : objects) {
		Thread.sleep(200);
		pb.step();
	}
}
```

**Comment by ctongfei** [comment]
Hello @eum2o -- this is not a bug of Progressbar, rather, this is because your PowerShell terminal uses the default "Cascadia" font, which does not support the box-drawing glyphs.  You can change the default font of your PowerShell to any of the following fonts and it should work:
Menlo, [Fira Mono](https://github.com/mozilla/Fira), [Source Code Pro](https://github.com/adobe-fonts/source-code-pro), [Iosevka](https://github.com/be5invis/Iosevka), [JetBrains Mono](https://www.jetbrains.com/lp/mono/) or [SF Mono](https://developer.apple.com/fonts/).
