### ISSUE TITLE
Feature: Support for Stacked/Styled Progress-Bars

### ISSUE THREAD

**Issue by drothmaler** [ctongfei/progressbar#157]
There are certain situation where I would like to have some kind of stacked progress bar. E.g. to show the result of the tasks or to visualize some other kind of distribution within the progress...

`Test     46% [xxx========>                        ] 20 failed; 70 successful / 200`
`Import   46% [xxxooo=====>                        ] 20 foo; 20 bar, 50 bazz / 200`

It wold be nice, if this could be added to this library.

**Comment by ctongfei** [comment]
Stacked bars are actually supported with the following usage:
```java
try (ProgressBar pb1 = new ProgressBar("Job1", max1); 
     ProgressBar pb2 = new ProgressBar("Job2", max2)) { 
    ... 
}
```

Styles can be customized by implementing your own `ProgressBarRenderer`. Right now you can use this customized renderer using this [deprecated constructor](https://javadoc.io/doc/me.tongfei/progressbar/latest/me.tongfei.progressbar/me/tongfei/progressbar/ProgressBar.html#%3Cinit%3E(java.lang.String,long,int,boolean,boolean,long,java.time.Duration,me.tongfei.progressbar.ProgressBarRenderer,me.tongfei.progressbar.ProgressBarConsumer)), but in the next version it'll be added to the builder pattern so that you can use 
```java
ProgressBar.builder().setRenderer(...)
```

Thanks!
